FROM --platform=linux/amd64 ruby:alpine3.16@sha256:a36324de633d5405923b087132c7728af0ec5f7c0f4efee72130b32520edcb44

RUN apk add --no-cache bash wget make libstdc++ gcc g++ automake autoconf gcompat

RUN wget https://github.com/sourcegraph/scip-ruby/releases/download/scip-ruby-v0.3.0/scip-ruby-x86_64-linux -O /usr/bin/scip-ruby && chmod +x /usr/bin/scip-ruby

COPY scip_indexer/autoindex.sh /usr/bin/scip-ruby-autoindex

RUN chmod +x /usr/bin/scip-ruby-autoindex

CMD ["/bin/sh"]
