method ::<Class:<root>>#<static-init> {

bb0[rubyRegionId=0, firstDead=38]():
    <self>: T.class_of(<root>) = cast(<self>: NilClass, T.class_of(<root>));
    <cfgAlias>$6: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$8: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$4: Sorbet::Private::Static::Void = <cfgAlias>$6: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$8: T.class_of(MyEnum))
    <cfgAlias>$11: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$13: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$9: Sorbet::Private::Static::Void = <cfgAlias>$11: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$13: T.class_of(MyEnum))
    <cfgAlias>$16: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$18: T.class_of(T::Enum) = alias <C Enum>
    <cfgAlias>$20: T.class_of(T) = alias <C T>
    <statTemp>$14: Sorbet::Private::Static::Void = <cfgAlias>$16: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$18: T.class_of(T::Enum))
    <cfgAlias>$24: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$26: T.class_of(NotAnEnum) = alias <C NotAnEnum>
    <statTemp>$22: Sorbet::Private::Static::Void = <cfgAlias>$24: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$26: T.class_of(NotAnEnum))
    <cfgAlias>$29: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$31: T.class_of(NotAnEnum) = alias <C NotAnEnum>
    <statTemp>$27: Sorbet::Private::Static::Void = <cfgAlias>$29: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$31: T.class_of(NotAnEnum))
    <cfgAlias>$35: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$37: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$33: Sorbet::Private::Static::Void = <cfgAlias>$35: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$37: T.class_of(EnumsDoEnum))
    <cfgAlias>$40: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$42: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$38: Sorbet::Private::Static::Void = <cfgAlias>$40: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$42: T.class_of(EnumsDoEnum))
    <cfgAlias>$45: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$47: T.class_of(T::Enum) = alias <C Enum>
    <cfgAlias>$49: T.class_of(T) = alias <C T>
    <statTemp>$43: Sorbet::Private::Static::Void = <cfgAlias>$45: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$47: T.class_of(T::Enum))
    <cfgAlias>$53: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$55: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$51: Sorbet::Private::Static::Void = <cfgAlias>$53: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$55: T.class_of(BadConsts))
    <cfgAlias>$58: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$60: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$56: Sorbet::Private::Static::Void = <cfgAlias>$58: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$60: T.class_of(BadConsts))
    <cfgAlias>$63: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$65: T.class_of(T::Enum) = alias <C Enum>
    <cfgAlias>$67: T.class_of(T) = alias <C T>
    <statTemp>$61: Sorbet::Private::Static::Void = <cfgAlias>$63: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$65: T.class_of(T::Enum))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:MyEnum>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C X>$34: MyEnum::X = alias <C X>
    <C Y>$57: MyEnum::Y = alias <C Y>
    <C Z>$81: MyEnum::Z = alias <C Z>
    <self>: T.class_of(MyEnum) = cast(<self>: NilClass, T.class_of(MyEnum));
    <cfgAlias>$6: T.class_of(T::Helpers) = alias <C Helpers>
    <statTemp>$3: T.class_of(MyEnum) = <self>: T.class_of(MyEnum).extend(<cfgAlias>$6: T.class_of(T::Helpers))
    <statTemp>$7: Sorbet::Private::Static::Void = <self>: T.class_of(MyEnum).abstract!()
    <statTemp>$9: Sorbet::Private::Static::Void = <self>: T.class_of(MyEnum).sealed!()
    <block-pre-call-temp>$13: Sorbet::Private::Static::Void = <self>: T.class_of(MyEnum).enums()
    <selfRestore>$14: T.class_of(MyEnum) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(MyEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(MyEnum), <C X>$34: MyEnum::X, <C Y>$57: MyEnum::Y, <C Z>$81: MyEnum::Z):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=2](<block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(MyEnum)):
    <statTemp>$11: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$13, enums>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=49](<self>: T.class_of(MyEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(MyEnum), <C X>$34: MyEnum::X, <C Y>$57: MyEnum::Y, <C Z>$81: MyEnum::Z):
    # outerLoops: 1
    <self>: T.class_of(MyEnum) = loadSelf(enums)
    <cfgAlias>$20: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$22: T.class_of(MyEnum::X) = alias <C X$1>
    <statTemp>$18: Sorbet::Private::Static::Void = <cfgAlias>$20: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$22: T.class_of(MyEnum::X))
    <cfgAlias>$25: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$27: T.class_of(MyEnum::X) = alias <C X$1>
    <statTemp>$23: Sorbet::Private::Static::Void = <cfgAlias>$25: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$27: T.class_of(MyEnum::X))
    <cfgAlias>$30: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$32: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$28: Sorbet::Private::Static::Void = <cfgAlias>$30: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$32: T.class_of(MyEnum))
    <cfgAlias>$36: T.class_of(MyEnum::X) = alias <C X$1>
    keep_for_ide$35: T.class_of(MyEnum::X) = <cfgAlias>$36
    keep_for_ide$35: T.class_of(MyEnum::X) = keep_for_ide$35
    <cfgAlias>$39: T.class_of(MyEnum::X) = alias <C X$1>
    <castTemp>$37: MyEnum::X = <cfgAlias>$39: T.class_of(MyEnum::X).new()
    <C X>$34: MyEnum::X = <castTemp>$37
    <cfgAlias>$43: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$45: T.class_of(MyEnum::Y) = alias <C Y$1>
    <statTemp>$41: Sorbet::Private::Static::Void = <cfgAlias>$43: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$45: T.class_of(MyEnum::Y))
    <cfgAlias>$48: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$50: T.class_of(MyEnum::Y) = alias <C Y$1>
    <statTemp>$46: Sorbet::Private::Static::Void = <cfgAlias>$48: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$50: T.class_of(MyEnum::Y))
    <cfgAlias>$53: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$55: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$51: Sorbet::Private::Static::Void = <cfgAlias>$53: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$55: T.class_of(MyEnum))
    <cfgAlias>$59: T.class_of(MyEnum::Y) = alias <C Y$1>
    keep_for_ide$58: T.class_of(MyEnum::Y) = <cfgAlias>$59
    keep_for_ide$58: T.class_of(MyEnum::Y) = keep_for_ide$58
    <cfgAlias>$62: T.class_of(MyEnum::Y) = alias <C Y$1>
    <statTemp>$63: String("y") = "y"
    <castTemp>$60: MyEnum::Y = <cfgAlias>$62: T.class_of(MyEnum::Y).new(<statTemp>$63: String("y"))
    <C Y>$57: MyEnum::Y = <castTemp>$60
    <cfgAlias>$67: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$69: T.class_of(MyEnum::Z) = alias <C Z$1>
    <statTemp>$65: Sorbet::Private::Static::Void = <cfgAlias>$67: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$69: T.class_of(MyEnum::Z))
    <cfgAlias>$72: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$74: T.class_of(MyEnum::Z) = alias <C Z$1>
    <statTemp>$70: Sorbet::Private::Static::Void = <cfgAlias>$72: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$74: T.class_of(MyEnum::Z))
    <cfgAlias>$77: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$79: T.class_of(MyEnum) = alias <C MyEnum>
    <statTemp>$75: Sorbet::Private::Static::Void = <cfgAlias>$77: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$79: T.class_of(MyEnum))
    <cfgAlias>$83: T.class_of(MyEnum::Z) = alias <C Z$1>
    keep_for_ide$82: T.class_of(MyEnum::Z) = <cfgAlias>$83
    keep_for_ide$82: T.class_of(MyEnum::Z) = keep_for_ide$82
    <cfgAlias>$86: T.class_of(MyEnum::Z) = alias <C Z$1>
    <castTemp>$84: MyEnum::Z = <cfgAlias>$86: T.class_of(MyEnum::Z).new(<self>: T.class_of(MyEnum))
    <C Z>$81: MyEnum::Z = <castTemp>$84
    <blockReturnTemp>$16: NilClass = nil
    <blockReturnTemp>$88: T.noreturn = blockreturn<enums> <blockReturnTemp>$16: NilClass
    <unconditional> -> bb2

}

method ::MyEnum::<Class:X>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(MyEnum::X) = cast(<self>: NilClass, T.class_of(MyEnum::X));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::MyEnum::<Class:Y>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(MyEnum::Y) = cast(<self>: NilClass, T.class_of(MyEnum::Y));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::MyEnum::<Class:Z>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(MyEnum::Z) = cast(<self>: NilClass, T.class_of(MyEnum::Z));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:NotAnEnum>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C X>$9: T.untyped = alias <C X>
    <C Y>$16: NotAnEnum = alias <C Y>
    <self>: T.class_of(NotAnEnum) = cast(<self>: NilClass, T.class_of(NotAnEnum));
    <block-pre-call-temp>$4: Sorbet::Private::Static::Void = <self>: T.class_of(NotAnEnum).enums()
    <selfRestore>$5: T.class_of(NotAnEnum) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(NotAnEnum), <block-pre-call-temp>$4: Sorbet::Private::Static::Void, <selfRestore>$5: T.class_of(NotAnEnum), <C X>$9: T.untyped, <C Y>$16: NotAnEnum):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=2](<block-pre-call-temp>$4: Sorbet::Private::Static::Void, <selfRestore>$5: T.class_of(NotAnEnum)):
    <returnMethodTemp>$2: T.untyped = Solve<<block-pre-call-temp>$4, enums>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.untyped
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=12](<self>: T.class_of(NotAnEnum), <block-pre-call-temp>$4: Sorbet::Private::Static::Void, <selfRestore>$5: T.class_of(NotAnEnum), <C X>$9: T.untyped, <C Y>$16: NotAnEnum):
    # outerLoops: 1
    <self>: T.class_of(NotAnEnum) = loadSelf(enums)
    <cfgAlias>$11: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$14: T.class_of(<Magic>) = alias <C <Magic>>
    <statTemp>$12: T.attached_class (of NotAnEnum) = <cfgAlias>$14: T.class_of(<Magic>).<self-new>(<self>: T.class_of(NotAnEnum))
    <C X>$9: T.attached_class (of NotAnEnum) = <cfgAlias>$11: T.class_of(<Magic>).<suggest-type>(<statTemp>$12: T.attached_class (of NotAnEnum))
    keep_for_ide$17: T.class_of(NotAnEnum) = <self>
    keep_for_ide$17: T.class_of(NotAnEnum) = keep_for_ide$17
    <cfgAlias>$20: T.class_of(<Magic>) = alias <C <Magic>>
    <castTemp>$18: T.attached_class (of NotAnEnum) = <cfgAlias>$20: T.class_of(<Magic>).<self-new>(<self>: T.class_of(NotAnEnum))
    <C Y>$16: NotAnEnum = cast(<castTemp>$18: T.attached_class (of NotAnEnum), NotAnEnum);
    <blockReturnTemp>$7: NotAnEnum = <C Y>$16
    <blockReturnTemp>$22: T.noreturn = blockreturn<enums> <blockReturnTemp>$7: NotAnEnum
    <unconditional> -> bb2

}

method ::EnumsDoEnum#something_outside {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: EnumsDoEnum = cast(<self>: NilClass, EnumsDoEnum);
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:EnumsDoEnum>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C X>$34: EnumsDoEnum::X = alias <C X>
    <C Y>$57: EnumsDoEnum::Y = alias <C Y>
    <C Z>$81: EnumsDoEnum::Z = alias <C Z>
    <self>: T.class_of(EnumsDoEnum) = cast(<self>: NilClass, T.class_of(EnumsDoEnum));
    <cfgAlias>$6: T.class_of(T::Helpers) = alias <C Helpers>
    <statTemp>$3: T.class_of(EnumsDoEnum) = <self>: T.class_of(EnumsDoEnum).extend(<cfgAlias>$6: T.class_of(T::Helpers))
    <statTemp>$7: Sorbet::Private::Static::Void = <self>: T.class_of(EnumsDoEnum).abstract!()
    <statTemp>$9: Sorbet::Private::Static::Void = <self>: T.class_of(EnumsDoEnum).sealed!()
    <block-pre-call-temp>$13: Sorbet::Private::Static::Void = <self>: T.class_of(EnumsDoEnum).enums()
    <selfRestore>$14: T.class_of(EnumsDoEnum) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(EnumsDoEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(EnumsDoEnum), <C X>$34: EnumsDoEnum::X, <C Y>$57: EnumsDoEnum::Y, <C Z>$81: EnumsDoEnum::Z):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=7](<block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(EnumsDoEnum)):
    <statTemp>$11: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$13, enums>
    <self>: T.class_of(EnumsDoEnum) = <selfRestore>$14
    <cfgAlias>$91: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$93: Symbol(:something_outside) = :something_outside
    <statTemp>$94: Symbol(:normal) = :normal
    <statTemp>$89: Symbol(:something_outside) = <cfgAlias>$91: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(EnumsDoEnum), <statTemp>$93: Symbol(:something_outside), <statTemp>$94: Symbol(:normal))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=49](<self>: T.class_of(EnumsDoEnum), <block-pre-call-temp>$13: Sorbet::Private::Static::Void, <selfRestore>$14: T.class_of(EnumsDoEnum), <C X>$34: EnumsDoEnum::X, <C Y>$57: EnumsDoEnum::Y, <C Z>$81: EnumsDoEnum::Z):
    # outerLoops: 1
    <self>: T.class_of(EnumsDoEnum) = loadSelf(enums)
    <cfgAlias>$20: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$22: T.class_of(EnumsDoEnum::X) = alias <C X$1>
    <statTemp>$18: Sorbet::Private::Static::Void = <cfgAlias>$20: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$22: T.class_of(EnumsDoEnum::X))
    <cfgAlias>$25: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$27: T.class_of(EnumsDoEnum::X) = alias <C X$1>
    <statTemp>$23: Sorbet::Private::Static::Void = <cfgAlias>$25: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$27: T.class_of(EnumsDoEnum::X))
    <cfgAlias>$30: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$32: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$28: Sorbet::Private::Static::Void = <cfgAlias>$30: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$32: T.class_of(EnumsDoEnum))
    <cfgAlias>$36: T.class_of(EnumsDoEnum::X) = alias <C X$1>
    keep_for_ide$35: T.class_of(EnumsDoEnum::X) = <cfgAlias>$36
    keep_for_ide$35: T.class_of(EnumsDoEnum::X) = keep_for_ide$35
    <cfgAlias>$39: T.class_of(EnumsDoEnum::X) = alias <C X$1>
    <castTemp>$37: EnumsDoEnum::X = <cfgAlias>$39: T.class_of(EnumsDoEnum::X).new()
    <C X>$34: EnumsDoEnum::X = <castTemp>$37
    <cfgAlias>$43: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$45: T.class_of(EnumsDoEnum::Y) = alias <C Y$1>
    <statTemp>$41: Sorbet::Private::Static::Void = <cfgAlias>$43: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$45: T.class_of(EnumsDoEnum::Y))
    <cfgAlias>$48: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$50: T.class_of(EnumsDoEnum::Y) = alias <C Y$1>
    <statTemp>$46: Sorbet::Private::Static::Void = <cfgAlias>$48: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$50: T.class_of(EnumsDoEnum::Y))
    <cfgAlias>$53: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$55: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$51: Sorbet::Private::Static::Void = <cfgAlias>$53: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$55: T.class_of(EnumsDoEnum))
    <cfgAlias>$59: T.class_of(EnumsDoEnum::Y) = alias <C Y$1>
    keep_for_ide$58: T.class_of(EnumsDoEnum::Y) = <cfgAlias>$59
    keep_for_ide$58: T.class_of(EnumsDoEnum::Y) = keep_for_ide$58
    <cfgAlias>$62: T.class_of(EnumsDoEnum::Y) = alias <C Y$1>
    <statTemp>$63: String("y") = "y"
    <castTemp>$60: EnumsDoEnum::Y = <cfgAlias>$62: T.class_of(EnumsDoEnum::Y).new(<statTemp>$63: String("y"))
    <C Y>$57: EnumsDoEnum::Y = <castTemp>$60
    <cfgAlias>$67: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$69: T.class_of(EnumsDoEnum::Z) = alias <C Z$1>
    <statTemp>$65: Sorbet::Private::Static::Void = <cfgAlias>$67: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$69: T.class_of(EnumsDoEnum::Z))
    <cfgAlias>$72: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$74: T.class_of(EnumsDoEnum::Z) = alias <C Z$1>
    <statTemp>$70: Sorbet::Private::Static::Void = <cfgAlias>$72: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$74: T.class_of(EnumsDoEnum::Z))
    <cfgAlias>$77: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$79: T.class_of(EnumsDoEnum) = alias <C EnumsDoEnum>
    <statTemp>$75: Sorbet::Private::Static::Void = <cfgAlias>$77: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$79: T.class_of(EnumsDoEnum))
    <cfgAlias>$83: T.class_of(EnumsDoEnum::Z) = alias <C Z$1>
    keep_for_ide$82: T.class_of(EnumsDoEnum::Z) = <cfgAlias>$83
    keep_for_ide$82: T.class_of(EnumsDoEnum::Z) = keep_for_ide$82
    <cfgAlias>$86: T.class_of(EnumsDoEnum::Z) = alias <C Z$1>
    <castTemp>$84: EnumsDoEnum::Z = <cfgAlias>$86: T.class_of(EnumsDoEnum::Z).new(<self>: T.class_of(EnumsDoEnum))
    <C Z>$81: EnumsDoEnum::Z = <castTemp>$84
    <blockReturnTemp>$16: NilClass = nil
    <blockReturnTemp>$88: T.noreturn = blockreturn<enums> <blockReturnTemp>$16: NilClass
    <unconditional> -> bb2

}

method ::EnumsDoEnum::<Class:X>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(EnumsDoEnum::X) = cast(<self>: NilClass, T.class_of(EnumsDoEnum::X));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::EnumsDoEnum::<Class:Y>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(EnumsDoEnum::Y) = cast(<self>: NilClass, T.class_of(EnumsDoEnum::Y));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::EnumsDoEnum::<Class:Z>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(EnumsDoEnum::Z) = cast(<self>: NilClass, T.class_of(EnumsDoEnum::Z));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:BadConsts>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C Before>$28: BadConsts::Before = alias <C Before>
    <C StaticField1>$35: Integer = alias <C StaticField1>
    <C Inside>$59: BadConsts::Inside = alias <C Inside>
    <C StaticField2>$66: Integer = alias <C StaticField2>
    <C After>$85: BadConsts::After = alias <C After>
    <C StaticField3>$92: Integer = alias <C StaticField3>
    <C StaticField4>$94: Integer = alias <C StaticField4>
    <self>: T.class_of(BadConsts) = cast(<self>: NilClass, T.class_of(BadConsts));
    <cfgAlias>$6: T.class_of(T::Helpers) = alias <C Helpers>
    <statTemp>$3: T.class_of(BadConsts) = <self>: T.class_of(BadConsts).extend(<cfgAlias>$6: T.class_of(T::Helpers))
    <statTemp>$7: Sorbet::Private::Static::Void = <self>: T.class_of(BadConsts).abstract!()
    <statTemp>$9: Sorbet::Private::Static::Void = <self>: T.class_of(BadConsts).sealed!()
    <cfgAlias>$14: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$16: T.class_of(BadConsts::Before) = alias <C Before$1>
    <statTemp>$12: Sorbet::Private::Static::Void = <cfgAlias>$14: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$16: T.class_of(BadConsts::Before))
    <cfgAlias>$19: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$21: T.class_of(BadConsts::Before) = alias <C Before$1>
    <statTemp>$17: Sorbet::Private::Static::Void = <cfgAlias>$19: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$21: T.class_of(BadConsts::Before))
    <cfgAlias>$24: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$26: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$22: Sorbet::Private::Static::Void = <cfgAlias>$24: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$26: T.class_of(BadConsts))
    <cfgAlias>$30: T.class_of(BadConsts::Before) = alias <C Before$1>
    keep_for_ide$29: T.class_of(BadConsts::Before) = <cfgAlias>$30
    keep_for_ide$29: T.class_of(BadConsts::Before) = keep_for_ide$29
    <cfgAlias>$33: T.class_of(BadConsts::Before) = alias <C Before$1>
    <castTemp>$31: BadConsts::Before = <cfgAlias>$33: T.class_of(BadConsts::Before).new()
    <C Before>$28: BadConsts::Before = <castTemp>$31
    <C StaticField1>$35: Integer(1) = 1
    <block-pre-call-temp>$38: Sorbet::Private::Static::Void = <self>: T.class_of(BadConsts).enums()
    <selfRestore>$39: T.class_of(BadConsts) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(BadConsts), <block-pre-call-temp>$38: Sorbet::Private::Static::Void, <selfRestore>$39: T.class_of(BadConsts), <C Inside>$59: BadConsts::Inside, <C StaticField2>$66: Integer, <C After>$85: BadConsts::After, <C StaticField3>$92: Integer, <C StaticField4>$94: Integer):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=23](<block-pre-call-temp>$38: Sorbet::Private::Static::Void, <selfRestore>$39: T.class_of(BadConsts), <C After>$85: BadConsts::After, <C StaticField3>$92: Integer, <C StaticField4>$94: Integer):
    <statTemp>$36: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$38, enums>
    <cfgAlias>$71: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$73: T.class_of(BadConsts::After) = alias <C After$1>
    <statTemp>$69: Sorbet::Private::Static::Void = <cfgAlias>$71: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$73: T.class_of(BadConsts::After))
    <cfgAlias>$76: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$78: T.class_of(BadConsts::After) = alias <C After$1>
    <statTemp>$74: Sorbet::Private::Static::Void = <cfgAlias>$76: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$78: T.class_of(BadConsts::After))
    <cfgAlias>$81: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$83: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$79: Sorbet::Private::Static::Void = <cfgAlias>$81: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$83: T.class_of(BadConsts))
    <cfgAlias>$87: T.class_of(BadConsts::After) = alias <C After$1>
    keep_for_ide$86: T.class_of(BadConsts::After) = <cfgAlias>$87
    keep_for_ide$86: T.class_of(BadConsts::After) = keep_for_ide$86
    <cfgAlias>$90: T.class_of(BadConsts::After) = alias <C After$1>
    <castTemp>$88: BadConsts::After = <cfgAlias>$90: T.class_of(BadConsts::After).new()
    <C After>$85: BadConsts::After = <castTemp>$88
    <C StaticField3>$92: Integer(3) = 3
    <cfgAlias>$96: T.class_of(Integer) = alias <C Integer>
    keep_for_ide$95: T.class_of(Integer) = <cfgAlias>$96
    keep_for_ide$95: T.class_of(Integer) = keep_for_ide$95
    <castTemp>$97: Integer(1) = 1
    <C StaticField4>$94: Integer = cast(<castTemp>$97: Integer(1), Integer);
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=19](<self>: T.class_of(BadConsts), <block-pre-call-temp>$38: Sorbet::Private::Static::Void, <selfRestore>$39: T.class_of(BadConsts), <C Inside>$59: BadConsts::Inside, <C StaticField2>$66: Integer, <C After>$85: BadConsts::After, <C StaticField3>$92: Integer, <C StaticField4>$94: Integer):
    # outerLoops: 1
    <self>: T.class_of(BadConsts) = loadSelf(enums)
    <cfgAlias>$45: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$47: T.class_of(BadConsts::Inside) = alias <C Inside$1>
    <statTemp>$43: Sorbet::Private::Static::Void = <cfgAlias>$45: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$47: T.class_of(BadConsts::Inside))
    <cfgAlias>$50: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$52: T.class_of(BadConsts::Inside) = alias <C Inside$1>
    <statTemp>$48: Sorbet::Private::Static::Void = <cfgAlias>$50: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$52: T.class_of(BadConsts::Inside))
    <cfgAlias>$55: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$57: T.class_of(BadConsts) = alias <C BadConsts>
    <statTemp>$53: Sorbet::Private::Static::Void = <cfgAlias>$55: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$57: T.class_of(BadConsts))
    <cfgAlias>$61: T.class_of(BadConsts::Inside) = alias <C Inside$1>
    keep_for_ide$60: T.class_of(BadConsts::Inside) = <cfgAlias>$61
    keep_for_ide$60: T.class_of(BadConsts::Inside) = keep_for_ide$60
    <cfgAlias>$64: T.class_of(BadConsts::Inside) = alias <C Inside$1>
    <castTemp>$62: BadConsts::Inside = <cfgAlias>$64: T.class_of(BadConsts::Inside).new()
    <C Inside>$59: BadConsts::Inside = <castTemp>$62
    <C StaticField2>$66: Integer(2) = 2
    <blockReturnTemp>$41: NilClass = nil
    <blockReturnTemp>$67: T.noreturn = blockreturn<enums> <blockReturnTemp>$41: NilClass
    <unconditional> -> bb2

}

method ::BadConsts::<Class:Before>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(BadConsts::Before) = cast(<self>: NilClass, T.class_of(BadConsts::Before));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::BadConsts::<Class:Inside>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(BadConsts::Inside) = cast(<self>: NilClass, T.class_of(BadConsts::Inside));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::BadConsts::<Class:After>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(BadConsts::After) = cast(<self>: NilClass, T.class_of(BadConsts::After));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

