method ::Object#rnd {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: Object = cast(<self>: NilClass, Object);
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:<root>>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <self>: T.class_of(<root>) = cast(<self>: NilClass, T.class_of(<root>));
    <cfgAlias>$6: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$8: T.class_of(Parent) = alias <C Parent>
    <statTemp>$4: Sorbet::Private::Static::Void = <cfgAlias>$6: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$8: T.class_of(Parent))
    <cfgAlias>$11: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$13: T.class_of(Parent) = alias <C Parent>
    <statTemp>$9: Sorbet::Private::Static::Void = <cfgAlias>$11: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$13: T.class_of(Parent))
    <cfgAlias>$17: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$19: T.class_of(Normal) = alias <C Normal>
    <statTemp>$15: Sorbet::Private::Static::Void = <cfgAlias>$17: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$19: T.class_of(Normal))
    <cfgAlias>$22: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$24: T.class_of(Normal) = alias <C Normal>
    <statTemp>$20: Sorbet::Private::Static::Void = <cfgAlias>$22: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$24: T.class_of(Normal))
    <cfgAlias>$27: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$29: T.class_of(Parent) = alias <C Parent>
    <statTemp>$25: Sorbet::Private::Static::Void = <cfgAlias>$27: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$29: T.class_of(Parent))
    <cfgAlias>$33: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$35: T.class_of(Generic) = alias <C Generic>
    <statTemp>$31: Sorbet::Private::Static::Void = <cfgAlias>$33: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$35: T.class_of(Generic))
    <cfgAlias>$38: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$40: T.class_of(Generic) = alias <C Generic>
    <statTemp>$36: Sorbet::Private::Static::Void = <cfgAlias>$38: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$40: T.class_of(Generic))
    <cfgAlias>$43: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$45: T.class_of(Parent) = alias <C Parent>
    <statTemp>$41: Sorbet::Private::Static::Void = <cfgAlias>$43: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$45: T.class_of(Parent))
    <cfgAlias>$48: T.class_of(Normal) = alias <C Normal>
    keep_for_ide$47: T.class_of(Normal) = <cfgAlias>$48
    keep_for_ide$47: T.class_of(Normal) = keep_for_ide$47
    <cfgAlias>$52: T.class_of(Normal) = alias <C Normal>
    <statTemp>$50: Normal = <cfgAlias>$52: T.class_of(Normal).new()
    <castTemp>$49: Normal = <statTemp>$50: Normal.returns_self()
    <statTemp>$46: Normal = cast(<castTemp>$49: Normal, Normal);
    <cfgAlias>$56: T.class_of(Generic) = alias <C Generic>
    <cfgAlias>$58: T.class_of(String) = alias <C String>
    keep_for_ide$54: Runtime object representing type: Generic[String] = <cfgAlias>$56: T.class_of(Generic).[](<cfgAlias>$58: T.class_of(String))
    keep_for_ide$54: Runtime object representing type: Generic[String] = keep_for_ide$54
    <cfgAlias>$63: T.class_of(Generic) = alias <C Generic>
    <cfgAlias>$65: T.class_of(String) = alias <C String>
    <statTemp>$61: Runtime object representing type: Generic[String] = <cfgAlias>$63: T.class_of(Generic).[](<cfgAlias>$65: T.class_of(String))
    <statTemp>$60: Generic[String] = <statTemp>$61: Runtime object representing type: Generic[String].new()
    <castTemp>$59: Generic[String] = <statTemp>$60: Generic[String].returns_self()
    <statTemp>$53: Generic[String] = cast(<castTemp>$59: Generic[String], Generic[String]);
    <cfgAlias>$69: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$71: T.class_of(B) = alias <C B>
    <statTemp>$67: Sorbet::Private::Static::Void = <cfgAlias>$69: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$71: T.class_of(B))
    <cfgAlias>$74: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$76: T.class_of(B) = alias <C B>
    <statTemp>$72: Sorbet::Private::Static::Void = <cfgAlias>$74: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$76: T.class_of(B))
    <cfgAlias>$80: T.class_of(Generic) = alias <C Generic>
    <cfgAlias>$82: T.class_of(String) = alias <C String>
    <statTemp>$78: Runtime object representing type: Generic[String] = <cfgAlias>$80: T.class_of(Generic).[](<cfgAlias>$82: T.class_of(String))
    a: Generic[String] = <statTemp>$78: Runtime object representing type: Generic[String].new()
    <cfgAlias>$87: T.class_of(B) = alias <C B>
    <ifTemp>$84: T::Boolean = a: Generic[String].is_a?(<cfgAlias>$87: T.class_of(B))
    <ifTemp>$84 -> (T::Boolean ? bb2 : bb4)

# backedges
# - bb7(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb2[rubyRegionId=0, firstDead=-1](<self>: T.class_of(<root>), a: T.all(Generic[String], B)):
    <cfgAlias>$90: T.class_of(T) = alias <C T>
    <cfgAlias>$93: T.class_of(Generic) = alias <C Generic>
    <cfgAlias>$95: T.class_of(String) = alias <C String>
    <statTemp>$91: Runtime object representing type: Generic[String] = <cfgAlias>$93: T.class_of(Generic).[](<cfgAlias>$95: T.class_of(String))
    <cfgAlias>$97: T.class_of(B) = alias <C B>
    keep_for_ide$88: Runtime object representing type: T.all(Generic[String], B) = <cfgAlias>$90: T.class_of(T).all(<statTemp>$91: Runtime object representing type: Generic[String], <cfgAlias>$97: T.class_of(B))
    keep_for_ide$88: Runtime object representing type: T.all(Generic[String], B) = keep_for_ide$88
    <castTemp>$98: T.all(Generic[String], B) = a: T.all(Generic[String], B).returns_self()
    <statTemp>$83: T.all(Generic[String], B) = cast(<castTemp>$98: T.all(Generic[String], B), T.all(Generic[String], B));
    <unconditional> -> bb4

# backedges
# - bb0(rubyRegionId=0)
# - bb2(rubyRegionId=0)
bb4[rubyRegionId=0, firstDead=-1](<self>: T.class_of(<root>)):
    <cfgAlias>$103: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$105: T.class_of(Array) = alias <C Array>
    <statTemp>$101: Sorbet::Private::Static::Void = <cfgAlias>$103: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$105: T.class_of(Array))
    <cfgAlias>$108: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$110: T.class_of(Array) = alias <C Array>
    <statTemp>$106: Sorbet::Private::Static::Void = <cfgAlias>$108: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$110: T.class_of(Array))
    <cfgAlias>$114: T.class_of(Integer) = alias <C Integer>
    <cfgAlias>$116: T.class_of(Integer) = alias <C Integer>
    <magic>$117: T.class_of(<Magic>) = alias <C <Magic>>
    keep_for_ide$112: [T.class_of(Integer), T.class_of(Integer)] = <magic>$117: T.class_of(<Magic>).<build-array>(<cfgAlias>$114: T.class_of(Integer), <cfgAlias>$116: T.class_of(Integer))
    keep_for_ide$112: [T.class_of(Integer), T.class_of(Integer)] = keep_for_ide$112
    <arrayTemp>$120: Integer(1) = 1
    <arrayTemp>$121: Integer(2) = 2
    <magic>$122: T.class_of(<Magic>) = alias <C <Magic>>
    <statTemp>$119: [Integer(1), Integer(2)] = <magic>$122: T.class_of(<Magic>).<build-array>(<arrayTemp>$120: Integer(1), <arrayTemp>$121: Integer(2))
    <castTemp>$118: [Integer(1), Integer(2)] = <statTemp>$119: [Integer(1), Integer(2)].returns_self()
    <statTemp>$111: [Integer, Integer] = cast(<castTemp>$118: [Integer(1), Integer(2)], [Integer, Integer]);
    <cfgAlias>$126: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$128: T.class_of(A) = alias <C A>
    <statTemp>$124: Sorbet::Private::Static::Void = <cfgAlias>$126: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$128: T.class_of(A))
    <cfgAlias>$131: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$133: T.class_of(A) = alias <C A>
    <statTemp>$129: Sorbet::Private::Static::Void = <cfgAlias>$131: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$133: T.class_of(A))
    <cfgAlias>$137: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$139: T.class_of(B) = alias <C B>
    <statTemp>$135: Sorbet::Private::Static::Void = <cfgAlias>$137: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$139: T.class_of(B))
    <cfgAlias>$142: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$144: T.class_of(B) = alias <C B>
    <statTemp>$140: Sorbet::Private::Static::Void = <cfgAlias>$142: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$144: T.class_of(B))
    <cfgAlias>$147: T.class_of(A) = alias <C A>
    s: A = <cfgAlias>$147: T.class_of(A).new()
    <cfgAlias>$150: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$152: Symbol(:rnd) = :rnd
    <statTemp>$153: Symbol(:normal) = :normal
    <statTemp>$148: Symbol(:rnd) = <cfgAlias>$150: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(<root>), <statTemp>$152: Symbol(:rnd), <statTemp>$153: Symbol(:normal))
    <unconditional> -> bb5

# backedges
# - bb4(rubyRegionId=0)
# - bb8(rubyRegionId=0)
# - bb9(rubyRegionId=0)
bb5[rubyRegionId=0, firstDead=-1](<self>: T.class_of(<root>), s: A):
    # outerLoops: 1
    <whileTemp>$155: T.untyped = <self>: T.class_of(<root>).rnd()
    <whileTemp>$155 -> (T.untyped ? bb8 : bb7)

# backedges
# - bb5(rubyRegionId=0)
bb7[rubyRegionId=0, firstDead=2](<self>: T.class_of(<root>), s: A):
    <statTemp>$163: NilClass = <self>: T.class_of(<root>).puts(s: A)
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb5(rubyRegionId=0)
bb8[rubyRegionId=0, firstDead=-1](<self>: T.class_of(<root>), s: A):
    # outerLoops: 1
    <cfgAlias>$161: T.class_of(B) = alias <C B>
    <ifTemp>$158: T::Boolean = s: A.is_a?(<cfgAlias>$161: T.class_of(B))
    <ifTemp>$158 -> (T::Boolean ? bb9 : bb5)

# backedges
# - bb8(rubyRegionId=0)
bb9[rubyRegionId=0, firstDead=-1](<self>: T.class_of(<root>), s: T.all(A, B)):
    # outerLoops: 1
    <statTemp>$162: T.all(A, B) = s
    s: T.all(A, B) = <statTemp>$162: T.all(A, B).returns_self()
    <unconditional> -> bb5

}

method ::Parent#returns_self {

bb0[rubyRegionId=0, firstDead=3]():
    <self>: Parent = cast(<self>: NilClass, Parent);
    <returnMethodTemp>$2: Parent = <self>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Parent
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:Parent>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <self>: T.class_of(Parent) = cast(<self>: NilClass, T.class_of(Parent));
    <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig) = alias <C ResolvedSig>
    <statTemp>$7: FalseClass = false
    <statTemp>$8: Symbol(:returns_self) = :returns_self
    <block-pre-call-temp>$9: Sorbet::Private::Static::Void = <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig).sig(<self>: T.class_of(Parent), <statTemp>$7: FalseClass, <statTemp>$8: Symbol(:returns_self))
    <selfRestore>$10: T.class_of(Parent) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(Parent), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Parent)):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=10](<block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Parent)):
    <statTemp>$3: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$9, sig>
    <self>: T.class_of(Parent) = <selfRestore>$10
    <cfgAlias>$21: T.class_of(T::Sig) = alias <C Sig>
    <cfgAlias>$23: T.class_of(T) = alias <C T>
    <statTemp>$18: T.class_of(Parent) = <self>: T.class_of(Parent).extend(<cfgAlias>$21: T.class_of(T::Sig))
    <cfgAlias>$26: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$28: Symbol(:returns_self) = :returns_self
    <statTemp>$29: Symbol(:normal) = :normal
    <statTemp>$24: Symbol(:returns_self) = <cfgAlias>$26: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(Parent), <statTemp>$28: Symbol(:returns_self), <statTemp>$29: Symbol(:normal))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=5](<self>: T.class_of(Parent), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Parent)):
    # outerLoops: 1
    <self>: T::Private::Methods::DeclBuilder = loadSelf(sig)
    <cfgAlias>$16: T.class_of(T) = alias <C T>
    <statTemp>$14: Runtime object representing type: T.untyped = <cfgAlias>$16: T.class_of(T).self_type()
    <blockReturnTemp>$12: T::Private::Methods::DeclBuilder = <self>: T::Private::Methods::DeclBuilder.returns(<statTemp>$14: Runtime object representing type: T.untyped)
    <blockReturnTemp>$17: T.noreturn = blockreturn<sig> <blockReturnTemp>$12: T::Private::Methods::DeclBuilder
    <unconditional> -> bb2

}

method ::<Class:Normal>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(Normal) = cast(<self>: NilClass, T.class_of(Normal));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::Generic#bad {

bb0[rubyRegionId=0, firstDead=7]():
    <self>: Generic[Generic::TM] = cast(<self>: NilClass, Generic[Generic::TM]);
    <cfgAlias>$5: T.class_of(Generic) = alias <C Generic>
    <cfgAlias>$8: T.class_of(T) = alias <C T>
    <statTemp>$6: Runtime object representing type: T.untyped = <cfgAlias>$8: T.class_of(T).untyped()
    <statTemp>$3: Runtime object representing type: Generic[T.untyped] = <cfgAlias>$5: T.class_of(Generic).[](<statTemp>$6: Runtime object representing type: T.untyped)
    <returnMethodTemp>$2: Generic[T.untyped] = <statTemp>$3: Runtime object representing type: Generic[T.untyped].new()
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Generic[T.untyped]
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:Generic>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <C TM>$28: Runtime object representing type: Generic::TM = alias <C TM>
    <self>: T.class_of(Generic) = cast(<self>: NilClass, T.class_of(Generic));
    <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig) = alias <C ResolvedSig>
    <statTemp>$7: FalseClass = false
    <statTemp>$8: Symbol(:bad) = :bad
    <block-pre-call-temp>$9: Sorbet::Private::Static::Void = <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig).sig(<self>: T.class_of(Generic), <statTemp>$7: FalseClass, <statTemp>$8: Symbol(:bad))
    <selfRestore>$10: T.class_of(Generic) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(Generic), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Generic)):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=11](<block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Generic)):
    <statTemp>$3: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$9, sig>
    <self>: T.class_of(Generic) = <selfRestore>$10
    <cfgAlias>$24: T.class_of(T::Generic) = alias <C Generic>
    <cfgAlias>$26: T.class_of(T) = alias <C T>
    <statTemp>$21: T.class_of(Generic) = <self>: T.class_of(Generic).extend(<cfgAlias>$24: T.class_of(T::Generic))
    <C TM>$28: T.untyped = <self>: T.class_of(Generic).type_member()
    <cfgAlias>$32: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$34: Symbol(:bad) = :bad
    <statTemp>$35: Symbol(:normal) = :normal
    <statTemp>$30: Symbol(:bad) = <cfgAlias>$32: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(Generic), <statTemp>$34: Symbol(:bad), <statTemp>$35: Symbol(:normal))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=7](<self>: T.class_of(Generic), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Generic)):
    # outerLoops: 1
    <self>: T::Private::Methods::DeclBuilder = loadSelf(sig)
    <cfgAlias>$16: T.class_of(Generic) = alias <C Generic>
    <cfgAlias>$19: T.class_of(T) = alias <C T>
    <statTemp>$17: Runtime object representing type: T.untyped = <cfgAlias>$19: T.class_of(T).self_type()
    <statTemp>$14: Runtime object representing type: Generic[T.untyped] = <cfgAlias>$16: T.class_of(Generic).[](<statTemp>$17: Runtime object representing type: T.untyped)
    <blockReturnTemp>$12: T::Private::Methods::DeclBuilder = <self>: T::Private::Methods::DeclBuilder.returns(<statTemp>$14: Runtime object representing type: Generic[T.untyped])
    <blockReturnTemp>$20: T.noreturn = blockreturn<sig> <blockReturnTemp>$12: T::Private::Methods::DeclBuilder
    <unconditional> -> bb2

}

method ::<Class:B>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(B) = cast(<self>: NilClass, T.class_of(B));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::Array#returns_self {

bb0[rubyRegionId=0, firstDead=3]():
    <self>: T::Array[Array::Elem] = cast(<self>: NilClass, T::Array[Array::Elem]);
    <returnMethodTemp>$2: T::Array[Array::Elem] = <self>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T::Array[Array::Elem]
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:Array>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <self>: T.class_of(Array) = cast(<self>: NilClass, T.class_of(Array));
    <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig) = alias <C ResolvedSig>
    <statTemp>$7: FalseClass = false
    <statTemp>$8: Symbol(:returns_self) = :returns_self
    <block-pre-call-temp>$9: Sorbet::Private::Static::Void = <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig).sig(<self>: T.class_of(Array), <statTemp>$7: FalseClass, <statTemp>$8: Symbol(:returns_self))
    <selfRestore>$10: T.class_of(Array) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(Array), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Array)):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=10](<block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Array)):
    <statTemp>$3: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$9, sig>
    <self>: T.class_of(Array) = <selfRestore>$10
    <cfgAlias>$21: T.class_of(T::Sig) = alias <C Sig>
    <cfgAlias>$23: T.class_of(T) = alias <C T>
    <statTemp>$18: T.class_of(Array) = <self>: T.class_of(Array).extend(<cfgAlias>$21: T.class_of(T::Sig))
    <cfgAlias>$26: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$28: Symbol(:returns_self) = :returns_self
    <statTemp>$29: Symbol(:normal) = :normal
    <statTemp>$24: Symbol(:returns_self) = <cfgAlias>$26: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(Array), <statTemp>$28: Symbol(:returns_self), <statTemp>$29: Symbol(:normal))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=5](<self>: T.class_of(Array), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(Array)):
    # outerLoops: 1
    <self>: T::Private::Methods::DeclBuilder = loadSelf(sig)
    <cfgAlias>$16: T.class_of(T) = alias <C T>
    <statTemp>$14: Runtime object representing type: T.untyped = <cfgAlias>$16: T.class_of(T).self_type()
    <blockReturnTemp>$12: T::Private::Methods::DeclBuilder = <self>: T::Private::Methods::DeclBuilder.returns(<statTemp>$14: Runtime object representing type: T.untyped)
    <blockReturnTemp>$17: T.noreturn = blockreturn<sig> <blockReturnTemp>$12: T::Private::Methods::DeclBuilder
    <unconditional> -> bb2

}

method ::<Class:A>#<static-init> {

bb0[rubyRegionId=0, firstDead=2]():
    <self>: T.class_of(A) = cast(<self>: NilClass, T.class_of(A));
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::B#returns_self {

bb0[rubyRegionId=0, firstDead=3]():
    <self>: B = cast(<self>: NilClass, B);
    <returnMethodTemp>$2: B = <self>
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: B
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:B>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <self>: T.class_of(B) = cast(<self>: NilClass, T.class_of(B));
    <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig) = alias <C ResolvedSig>
    <statTemp>$7: FalseClass = false
    <statTemp>$8: Symbol(:returns_self) = :returns_self
    <block-pre-call-temp>$9: Sorbet::Private::Static::Void = <cfgAlias>$5: T.class_of(Sorbet::Private::Static::ResolvedSig).sig(<self>: T.class_of(B), <statTemp>$7: FalseClass, <statTemp>$8: Symbol(:returns_self))
    <selfRestore>$10: T.class_of(B) = <self>
    <unconditional> -> bb2

# backedges
# - bb3(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
# - bb5(rubyRegionId=1)
bb2[rubyRegionId=1, firstDead=-1](<self>: T.class_of(B), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(B)):
    # outerLoops: 1
    <block-call> -> (NilClass ? bb5 : bb3)

# backedges
# - bb2(rubyRegionId=1)
bb3[rubyRegionId=0, firstDead=10](<block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(B)):
    <statTemp>$3: Sorbet::Private::Static::Void = Solve<<block-pre-call-temp>$9, sig>
    <self>: T.class_of(B) = <selfRestore>$10
    <cfgAlias>$21: T.class_of(T::Sig) = alias <C Sig>
    <cfgAlias>$23: T.class_of(T) = alias <C T>
    <statTemp>$18: T.class_of(B) = <self>: T.class_of(B).extend(<cfgAlias>$21: T.class_of(T::Sig))
    <cfgAlias>$26: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$28: Symbol(:returns_self) = :returns_self
    <statTemp>$29: Symbol(:normal) = :normal
    <statTemp>$24: Symbol(:returns_self) = <cfgAlias>$26: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(B), <statTemp>$28: Symbol(:returns_self), <statTemp>$29: Symbol(:normal))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb2(rubyRegionId=1)
bb5[rubyRegionId=1, firstDead=5](<self>: T.class_of(B), <block-pre-call-temp>$9: Sorbet::Private::Static::Void, <selfRestore>$10: T.class_of(B)):
    # outerLoops: 1
    <self>: T::Private::Methods::DeclBuilder = loadSelf(sig)
    <cfgAlias>$16: T.class_of(T) = alias <C T>
    <statTemp>$14: Runtime object representing type: T.untyped = <cfgAlias>$16: T.class_of(T).self_type()
    <blockReturnTemp>$12: T::Private::Methods::DeclBuilder = <self>: T::Private::Methods::DeclBuilder.returns(<statTemp>$14: Runtime object representing type: T.untyped)
    <blockReturnTemp>$17: T.noreturn = blockreturn<sig> <blockReturnTemp>$12: T::Private::Methods::DeclBuilder
    <unconditional> -> bb2

}

