# Loosely based off .sorbet-buildkite/pipeline.yaml

s3-settings: &s3-settings
  backend: s3
  s3:
    bucket: sourcegraph_buildkite_cache
    endpoint: https://storage.googleapis.com
    profile: buildkite
    region: us-central1
  tarball: {}

bazel-full-cache: &bazel-full-cache
  id: bazel-full
  key: "bazel-full-{{ env.BUILDKITE_BRANCH }}-{{ env.BUILDKITE_COMMIT }}"
  restore-keys:
    - "bazel-full-{{ env.BUILDKITE_BRANCH }}-{{ env.BUILDKITE_COMMIT }}"
    - "bazel-full-{{ env.BUILDKITE_COMMIT }}"
    - "bazel-full-"
  paths:
    - /usr/local/var/bazelcache
  <<: *s3-settings

steps:
  - label: ":linux: test-indexer.sh"
    command: .buildkite/test-indexer.sh
    artifact_paths:
      - "_out_/profile*.json"
    agents:
      queue: stateless
    env:
      AWS_CONFIG_FILE: /buildkite/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /buildkite/.aws/credentials
    plugins:
    - https://github.com/sourcegraph/cache-buildkite-plugin.git#master:
        <<: *bazel-full-cache
        compress: true
        compress-program: pigz

  - wait: ~

# Success Phase - Allow the PR to be merged
  - label: "All tests and builds succeeded"
    command: .buildkite/all-succeeded.sh

  - wait: ~
