method ::<Class:<root>>#<static-init> {

bb0[rubyRegionId=0, firstDead=8]():
    <self>: T.class_of(<root>) = cast(<self>: NilClass, T.class_of(<root>));
    <cfgAlias>$5: T.class_of(<Magic>) = alias <C <Magic>>
    <cfgAlias>$7: T.class_of(TestIVar) = alias <C TestIVar>
    <statTemp>$3: Sorbet::Private::Static::Void = <cfgAlias>$5: T.class_of(<Magic>).<define-top-class-or-module>(<cfgAlias>$7: T.class_of(TestIVar))
    <cfgAlias>$10: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$12: T.class_of(TestIVar) = alias <C TestIVar>
    <statTemp>$8: Sorbet::Private::Static::Void = <cfgAlias>$10: T.class_of(Sorbet::Private::Static).keep_for_ide(<cfgAlias>$12: T.class_of(TestIVar))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestIVar#initialize {

bb0[rubyRegionId=0, firstDead=9]():
    @foo$3: Integer = alias @foo
    <self>: TestIVar = cast(<self>: NilClass, TestIVar);
    <cfgAlias>$5: T.class_of(Integer) = alias <C Integer>
    keep_for_ide$4: T.class_of(Integer) = <cfgAlias>$5
    keep_for_ide$4: T.class_of(Integer) = keep_for_ide$4
    <castTemp>$6: Integer(0) = 0
    @foo$3: Integer = cast(<castTemp>$6: Integer(0), Integer);
    <returnMethodTemp>$2: Integer = @foo$3
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Integer
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::TestIVar#test {

bb0[rubyRegionId=0, firstDead=5]():
    @foo$3: Integer = alias @foo
    <self>: TestIVar = cast(<self>: NilClass, TestIVar);
    @foo$3: Integer = nil
    <returnMethodTemp>$2: Integer = @foo$3
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: Integer
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

method ::<Class:TestIVar>#<static-init> {

bb0[rubyRegionId=0, firstDead=10]():
    <self>: T.class_of(TestIVar) = cast(<self>: NilClass, T.class_of(TestIVar));
    <cfgAlias>$5: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$7: Symbol(:initialize) = :initialize
    <statTemp>$8: Symbol(:normal) = :normal
    <statTemp>$3: Symbol(:initialize) = <cfgAlias>$5: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(TestIVar), <statTemp>$7: Symbol(:initialize), <statTemp>$8: Symbol(:normal))
    <cfgAlias>$11: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <statTemp>$13: Symbol(:test) = :test
    <statTemp>$14: Symbol(:normal) = :normal
    <statTemp>$9: Symbol(:test) = <cfgAlias>$11: T.class_of(Sorbet::Private::Static).keep_def(<self>: T.class_of(TestIVar), <statTemp>$13: Symbol(:test), <statTemp>$14: Symbol(:normal))
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: NilClass
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

}

