name: Lint
on:
  push:
    branches:
      - scip-ruby/master
  pull_request:
    branches:
      - scip-ruby/master

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - name: Format Bazel files
        run: |
          set -e
          GOBIN="$PWD" go install github.com/bazelbuild/buildtools/buildifier@latest
          git ls-files -- '**.bzl' '**/BUILD' WORKSPACE | xargs ./buildifier -mode=diff
      - name: Lint workflow files
        run: |
          go install github.com/rhysd/actionlint/cmd/actionlint@latest
          actionlint .github/workflows/*.yml
