name: Lint
on:
  push:
    branches:
      - scip-ruby/master
  pull_request:
    branches:
      - scip-ruby/master

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v3
      - name: Format Bazel files
        run: |
          ./tools/scripts/format_build_files.sh
          if ! git diff --quiet; then
            git diff
            echo ""
            echo "-----------------------------------------------------"
            echo "Re-run ./tools/scripts/format_build_files.sh and push"
            echo "-----------------------------------------------------"
            exit 1
          fi
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - name: Lint workflow files
        run: |
          go install github.com/rhysd/actionlint/cmd/actionlint@latest
          actionlint .github/workflows/*.yml
